baseURL = "https://giography.vercel.app/"
copyright = "© Giovani Valdriz | 2025"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Asia/Manila"
timeout = "1200s"
title = "giography"

[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50

[params]
  defaultTheme = "light"
  description = "Official Photofolio of giography"
  title = "giography"
  [params.author]
    email = "zirdl.giography@gmail.com"
    name = "gio"
  [params.socialIcons]
    email = "mailto:zirdl.giography@gmail.com"
    facebook = "https://www.facebook.com/giography.zirdl"
    instagram = "#"
    website = "#"
    #mastodon = "https://example.com"
  # [params.search]
  #   filter_taxonomies = false
  #   filter_years = false
  #   ignore_location = true
  #   index_all_pages = false
  #   max_results = 20
  #   threshold = 0.3
  #   expand_results_meta = true
  #   histories = false

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  # [[menu.footer]]
  #   name = ""
  #   url = "https://github.com/zirdl/"
  #   weight = 3

[services]
  [services.rss]
    limit = 5
